### ISSUE TITLE
Hello! Can this code run on windows system?

### ISSUE THREAD

**Issue by zhongdigood** [ThGaskin/NeuralABM#33]

**Comment by ThGaskin** [comment]
Hello -- unfortunately not, see the README, and also [this closed issue](https://github.com/ThGaskin/NeuralABM/issues/31). Do let me know if you need any help!

**Comment by ThGaskin** [comment]
I think they solved it by running a virtual Linux machine

**Comment by zhongdigood** [comment]
When I run utopya run SIR on Ubuntu, I get the following error:

**Comment by zhongdigood** [comment]
When I run utopya run SIR on Ubuntu, I get the following error:
``INFO     run               Parsing additional command line arguments ...
NOTE     run               Updates to meta configuration:

{debug_level: 0}

REMARK   entry             Getting info bundle for model 'SIR' ...
REMARK   entry               ... selecting only registered info bundle:  from_manifest_file
PROGRESS model             Initializing Model instance for 'SIR' ...
NOTE     model               Project:        NeuralABM
NOTE     model               Framework:      None
PROGRESS multiverse        Initializing Multiverse for 'SIR' model ...
INFO     multiverse        Building meta-configuration ...
NOTE     multiverse        Using default run configuration:
  /home/weipeng/NeuralABM-main/models/SIR/SIR_cfg.yml

INFO     multiverse        Built meta configuration.
REMARK   multiverse          Debug level:  0
NOTE     multiverse        Run directory:
  /home/weipeng/utopya_output/SIR/230607-133142
INFO     multiverse        Performing backups ...
NOTE     multiverse          Backed up meta configuration.
NOTE     multiverse          Backed up full parameter space and metadata.
NOTE     multiverse          Backed up all involved configuration files.
WARNING  gitinfo           No git dir found
NOTE     multiverse          Stored project's git info and patch.
INFO     multiverse        Validating 13 parameters ...
REMARK   multiverse        Parameter space volume:      0
NOTE     multiverse        All parameters valid.
Traceback (most recent call last):
  File "/home/weipeng/env1/bin/utopya", line 8, in <module>
    sys.exit(cli())
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya_cli/run.py", line 199, in run
    mv = model.create_mv(run_cfg_path=run_cfg, **update_dict)
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/model.py", line 298, in create_mv
    mv = Multiverse(
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 189, in __init__
    self._prepare_executable(**self.meta_cfg["executable_control"])
  File "/home/weipeng/env1/lib/python3.10/site-packages/utopya/multiverse.py", line 1074, in _prepare_executable
    raise PermissionError(
PermissionError: The specified executable path for model 'SIR' does not point to an executable file. Did you set the correct access rights? Use chmod to adjust access rights.
Executable path:  {execpath}``

**Comment by zhongdigood** [comment]
> Weird -- something's messed up somewhere. Can you do `git checkout main` and give me the terminal output?
> 
> If you've not changed anything you want to keep -- maybe just delete the folder and re-clone the repo?

```
(env1) ➜  NeuralABM git:(main) ✗ git checkout main
M       models/SIR/run.py
Already on 'main'
Your branch is up to date with 'origin/main'.`

**Comment by ThGaskin** [comment]
Weird -- and difficult for me fix remotely. Something in your git config is messed up; I suggest a hard reset

**Comment by zhongdigood** [comment]
> re-clone it using git

This is my first time using WSL and git, and I feel like I know too little about git. The "re-clone it using git" you said refers to delete "git" in ubuntu and re-clone `git clone https://github.com/ThGaskin/NeuralABM`?

**Comment by ThGaskin** [comment]
No -- don't delete git. I just mean manually delete the 'NeuralABM' folder you're currently using, and then do `git clone https://github.com/ThGaskin/NeuralABM`

**Comment by zhongdigood** [comment]
I just deleted the 'NeuralABM' folder and redo.  The warnings "git warnings" really disappear! Thank you so much.
Now I run "utopya run SIR" and there is only the following warning (although I don't know if it is fatal):

**ERROR    plot_mngr         An error occurred during plotting with UniversePlotCreator for 'state'! For a full error traceback, specify `debug: True` in the plot configuration or run the PlotManager in debug mode.
ValueError: The writer 'ffmpeg' is not available on your system! Available writers: pillow, html, frames**

```  
  uni0 out:  PROGRESS    Completed epoch 997 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 998 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 999 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Completed epoch 1000 / 1000;    current loss: 0.3333333432674408
  uni0 out:  PROGRESS    Generating predicted dataset ...
  uni0 out:  INFO    Simulation run finished.
  uni0 out:  INFO    Wrapping up ...
  uni0 out:  SUCCESS    All done.
    ╠░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╣   0.0% |  4m 17s elapsed | ~      ∞ left 
    ╠▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╣ 100.0% | finished in 4m 18s 

PROGRESS workermanager     Finished working. Total tasks worked on: 1
SUCCESS  multiverse        Finished simulation run. Wohoo. :)

PROGRESS eval              Beginning evaluation: loading data and starting PlotManager ...

HILIGHT  data_mngr         Loading 4 data entries ...
PROGRESS data_mngr         Loading data entry 'cfg' ...
NOTE     data_mngr         Found 5 files with a total size of 26.6 kiB.
PROGRESS data_mngr         Loaded all data for entry 'cfg' in 0.01s.

PROGRESS data_mngr         Loading data entry 'pspace' ...
NOTE     data_mngr         Found 1 file with a total size of 785 B.
PROGRESS data_mngr         Loaded all data for entry 'pspace' in 0.00s.

PROGRESS data_mngr         Loading data entry 'uni_cfg' ...
NOTE     data_mngr         Found 1 file with a total size of 922 B.
REMARK   data_mngr         Not loading in parallel: there are only 1 < 1000 files to load.
PROGRESS data_mngr         Loaded all data for entry 'uni_cfg' in 0.00s.

PROGRESS data_mngr         Loading data entry 'data' ...
NOTE     data_mngr         Found 1 file with a total size of 2.0 MiB.
PROGRESS data_mngr         Loaded all data for entry 'data' in 0.02s.

SUCCESS  data_mngr         Successfully loaded 4 data entries.
INFO     eval              
Tree of DataManager 'SIR_data', 2 members, 0 attributes
 └┬ multiverse                                              <MultiverseGroup, 1 member, 1 attribute>
    └─ 0                                                    <UniverseGroup, 2 members, 0 attributes>
       └┬ cfg                                               <MutableMappingContainer, 1 attribute>
        └ data                                              <OrderedDataGroup, 1 member, 0 attributes>
          └─ SIR                                            <OrderedDataGroup, 8 members, 0 attributes>
             └┬ kinds                                       <XarrayDC, proxy (hdf5), float32, (time: 200, agent_id: 150), 3 attributes>
              ├ loss                                        <XarrayDC, proxy (hdf5), float32, (time: 198999, training_loss: 1), 3 attributes>
              ├ position                                    <XarrayDC, proxy (hdf5), float32, (time: 200, agent_id: 150, coords: 2), 5 attributes>
              ├ predicted_counts                            <XarrayDC, proxy (hdf5), float64, (time: 202, kind: 3, kinds: 1), 6 attributes>
              ├ predicted_infection_rate                    <XarrayDC, proxy (hdf5), float32, (time: 198999, p_infect: 1), 3 attributes>
              ├ predicted_infection_time                    <XarrayDC, proxy (hdf5), float32, (time: 198999, t_infectious: 1), 3 attributes>
              ├ predicted_noise                             <XarrayDC, proxy (hdf5), float32, (time: 198999, noise: 1), 3 attributes>
              └ true_counts                                 <XarrayDC, proxy (hdf5), float64, (time: 200, kind: 3, kinds: 1), 6 attributes>
  └ cfg                                                     <OrderedDataGroup, 5 members, 0 attributes>
    └┬ base                                                 <MutableMappingContainer, 1 attribute>
     ├ ...                                                  ... (3 more) ...
     └ update                                               <MutableMappingContainer, 1 attribute>

HILIGHT  plotmanager       Now creating plots for 'SIR' model ...
NOTE     plotmanager       Using default plots configuration:
  /home/weipeng/NeuralABM-main/models/SIR/SIR_plots.yml

HILIGHT  plot_mngr         Performing plots from 11 plot configuration entries:
NOTE     plot_mngr         Have (at least) the following 11 plots to perform:
  - state                                               (universe, 1 plot)
  - densities                                           (universe, 1 plot)
  - loss                                                (universe, 1 plot)
  - predictions/p_infectious                            (universe, 1 plot)
  - predictions/t_infectious                            (universe, 1 plot)
  - predictions/noise                                   (universe, 1 plot)
  - loss_density/p_infectious                           (universe, 1 plot)
  - loss_density/t_infectious                           (universe, 1 plot)
  - marginals/p_infectious                              (universe, 1 plot)
  - marginals/t_infectious                              (universe, 1 plot)
  - marginals/noise                                     (universe, 1 plot)

PROGRESS plot_mngr         Plotting 'state' ...
REMARK   pyplot            Using custom style context with 18 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 8 nodes set up in 0.0s.
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 5 tags on DAG with 8 nodes ...
REMARK   dag                  1/5:  'uni'  ...
REMARK   dag                  2/5:  'kinds'  ...
REMARK   dag                  3/5:  'x'  ...
REMARK   dag                  4/5:  'y'  ...
REMARK   dag                  5/5:  'data'  ...
NOTE     dag               Computed 5 tags in 0.01s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.00081  ±  0.0013    (0       | 0.0034 )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
ERROR    plot_mngr         An error occurred during plotting with UniversePlotCreator for 'state'! For a full error traceback, specify `debug: True` in the plot configuration or run the PlotManager in debug mode.

ValueError: The writer 'ffmpeg' is not available on your system! Available writers: pillow, html, frames
PROGRESS plot_mngr         Plotting 'densities' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 6 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 6 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.01s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.0007   ±  0.0012    (0       | 0.0028 )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
NOTE     generic           Facet grid plot of kind 'line' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'densities' plot in 0.8s.

PROGRESS plot_mngr         Plotting 'loss' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 2 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 2 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.00s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   2.2e-05  ±  2.2e-05   (0       | 4.4e-05)
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
NOTE     generic           Facet grid plot of kind 'line' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'loss' plot in 1.5s.

PROGRESS plot_mngr         Plotting 'predictions/p_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 3 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 3 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.02s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.0075   ±  0.011     (0       | 0.023  )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
NOTE     generic           Facet grid plot of kind 'line' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
REMARK   mpl               Using custom labels:  $p_\mathrm{infect}$
REMARK   mpl               Have 0 handles and 1 labels available for the legend.
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'predictions/p_infectious' plot in 0.7s.

PROGRESS plot_mngr         Plotting 'predictions/t_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 3 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 3 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.02s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.007    ±  0.0099    (0       | 0.021  )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
NOTE     generic           Facet grid plot of kind 'line' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
REMARK   mpl               Using custom labels:  $t_\mathrm{infect}$
REMARK   mpl               Have 0 handles and 1 labels available for the legend.
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'predictions/t_infectious' plot in 1.0s.

PROGRESS plot_mngr         Plotting 'predictions/noise' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 3 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 3 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.02s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.0069   ±  0.0097    (0       | 0.021  )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
NOTE     generic           Facet grid plot of kind 'line' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
REMARK   mpl               Using custom labels:  $\sigma$
REMARK   mpl               Have 0 handles and 1 labels available for the legend.
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'predictions/noise' plot in 0.5s.

PROGRESS plot_mngr         Plotting 'loss_density/p_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 8 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 8 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.01s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.00056  ±  0.0012    (0       | 0.0036 )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
REMARK   color_mngr        Configuring a linear colormap 'from values'. 
NOTE     generic           Facet grid plot of kind 'scatter' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'loss_density/p_infectious' plot in 2.6s.

PROGRESS plot_mngr         Plotting 'loss_density/t_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 8 nodes set up in 0.0s.
REMARK   base              Tags that are required by the plot function:  data
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 1 tag on DAG with 8 nodes ...
REMARK   dag                  1/1:  'data'  ...
NOTE     dag               Computed 1 tag in 0.00s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.00013  ±  0.00023   (0       | 0.00071)
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'facet_grid' ...
REMARK   color_mngr        Configuring a linear colormap 'from values'. 
NOTE     generic           Facet grid plot of kind 'scatter' now commencing ...
NOTE     base              Plotting function 'facet_grid' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'loss_density/t_infectious' plot in 2.6s.

PROGRESS plot_mngr         Plotting 'marginals/p_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 10 nodes set up in 0.0s.
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 4 tags on DAG with 10 nodes ...
REMARK   dag                  1/4:  'uni'  ...
REMARK   dag                  2/4:  'loss'  ...
REMARK   dag                  3/4:  'param1'  ...
REMARK   dag                  4/4:  'data'  ...
NOTE     dag               Computed 4 tags in 0.71s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.071    ±  0.21      (0       | 0.71   )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'plot_prob_density' ...
NOTE     base              Plotting function 'plot_prob_density' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'marginals/p_infectious' plot in 0.9s.

PROGRESS plot_mngr         Plotting 'marginals/t_infectious' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 10 nodes set up in 0.0s.
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 4 tags on DAG with 10 nodes ...
REMARK   dag                  1/4:  'uni'  ...
REMARK   dag                  2/4:  'loss'  ...
REMARK   dag                  3/4:  'param1'  ...
REMARK   dag                  4/4:  'data'  ...
NOTE     dag               Computed 4 tags in 0.71s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.071    ±  0.21      (0       | 0.71   )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'plot_prob_density' ...
NOTE     base              Plotting function 'plot_prob_density' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'marginals/t_infectious' plot in 1.0s.

PROGRESS plot_mngr         Plotting 'marginals/noise' ...
REMARK   pyplot            Using custom style context with 17 entries ...
NOTE     psp               Using data of:        UniverseGroup '0'
NOTE     base              Setting up data transformation framework ...
NOTE     base              TransformationDAG with 10 nodes set up in 0.0s.
INFO     base              Computing data transformation results ...
NOTE     dag               Computing result of 4 tags on DAG with 10 nodes ...
REMARK   dag                  1/4:  'uni'  ...
REMARK   dag                  2/4:  'loss'  ...
REMARK   dag                  3/4:  'param1'  ...
REMARK   dag                  4/4:  'data'  ...
NOTE     dag               Computed 4 tags in 0.71s.
REMARK   dag               Profiling results per node:  mean ± std (min|max) [s]
                  compute   0.071    ±  0.21      (0       | 0.71   )
             cache_lookup   nan      ±  nan       (nan     | nan    )
            cache_writing   nan      ±  nan       (nan     | nan    )
REMARK   base              Finished computing data transformation results.
REMARK   _dag_utils        No placeholders found to resolve.
INFO     base              Now calling plotting function 'plot_prob_density' ...
NOTE     base              Plotting function 'plot_prob_density' returned.
INFO     pyplot            Invoking helpers ...
NOTE     pyplot            Saving figure ...
REMARK   pyplot            Figure saved.
PROGRESS plot_mngr         Performed 'marginals/noise' plot in 1.0s.

SUCCESS  plot_mngr         Performed plots from 11 plot configurations in 12.9s.

SUCCESS  eval              All done.`

**Comment by zhongdigood** [comment]
In addition, I still don't know how to display the results. For example, what command should I run to make these graphs appear?
![image](https://github.com/ThGaskin/NeuralABM/assets/49575602/5b75f7db-ab93-47f9-b6ae-19f1885b3106)

**Comment by ThGaskin** [comment]
Ffmpeg is an audio and video writer for animations, and is used to plot the ABM animation. You can install on Linux by running 

```
sudo apt install ffmpeg
```
You can typically resolve these sorts of errors by googling. 

How to find the plots: everything is automatically plotted and saved in your home directory — there should be a folder there called `utopya_output` with time-stamped folders containing the plots. 

I recommend you peruse the README, and perhaps even the full utopia tutorial as linked in the README (always using the command `utopya` instead of `utopia`)

**Comment by ThGaskin** [comment]
Does this work?

**Comment by zhongdigood** [comment]
I ran "sudo apt install ffmpeg" as you suggested and now there are no warnings. In other words, using WSL2 and VS code on the windows system can run your code and reproduce the results of your paper!!

As for the results and image output, I successfully found the output results according to your suggestion, as follows:
![image](https://github.com/ThGaskin/NeuralABM/assets/49575602/de64331f-f0d8-48f5-b4e1-33b5cc1d5934)

You are the most enthusiastic scientific researcher I have ever met to reply to strangers. Thank you very much for your help!

**Comment by ThGaskin** [comment]
Thanks! I take reproducibility and adaptability very seriously -- there is no point publishing scientific papers if results cannot be reproduced and methods are not accessible to further development by others. I hope the code and tools are of use to you, and do let me know if you need further assistance. Best, Thomas

**Comment by ThGaskin** [comment]
A colleague and I today tried to adapt utopya for Windows -- it looks extremely difficult, because Windows is so different from unix systems, so I don't know when we'll be able get it to run utopya on windows without WSL ... Sorry! But do let me know if you need any help -- you also have my e-mail from the papers right?

**Comment by zhongdigood** [comment]
Applying utopya on windows seems to be difficult. Since the laboratory equipment uses Windows, if the laboratory computer also uses WSL, this will involve information interaction between different systems. This also seems to be difficult. I saw your email on your published paper. It would be great if I could contact you directly by email!

**Comment by ThGaskin** [comment]
Please do send me an email.

Are you trying to on-line parameter calibration?
